config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, controllers: { sessions: "authors/sessions" }
  resources :articles do
    resources :comments
  end
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  paginates_per 5
  belongs_to :author
  has_many :comments, dependent: :nullify
  validates :name, length: { maximum: 255 }
  has_attached_file :image, :styles => { :large => "300x300>", :small => "150x150#", :avatar => "100x100#" }, :default_url => "", :convert_options => {:large => "-gravity center -extent 300x300", :small => "-gravity center -extent 150x150", :avatar => "-gravity center -extent 100x100"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
  validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 5.megabytes


  has_attached_file :video, :styles => {
    :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 1 }
  }, :default_url => "", :processors => [:transcoder]
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/x-flv", "video/avi"]
  validates_attachment_file_name :video, :matches => [/mp4\Z/, /flv\Z/, /avi\Z/]
  validates_with AttachmentSizeValidator, :attributes => :video, :less_than => 30.megabytes

  def image_url
    image.url(:large)
  end

  def video_thumb_url
    video.url(:thumb)
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource except: [:create]
  before_action :get_article, only: [:edit, :update, :show, :destroy]
  before_action :get_id_param, only: [:update, :destroy]
  before_action :authenticate_author!

  def index
    @articles = Article.page(params[:page]).per(3).order("id desc")
    @article = Article.new
  end

  def new
    @article = Article.new
  end

  def create
    author = AuthorService.new().get_author(params[:article][:author_id])
    @article = get_article_service.create_article(author, get_article_params)
    MailerJob.perform_later
    respond_to do |format|
       format.json {
        render :json => @article.to_json(:methods => [:image_url])
       }
    end
  end

  def edit
  end

  def update
    get_article_service.update_article(@article, get_article_params)
  end

  def show
    @comments = @article.comments
  end

  def destroy
    get_article_service.destroy_article(@article)
  end

  private
    def get_article_service
      article_service = ArticleService.new()
    end

    def get_article_params
      params.require(:article).permit(:name, :text, :image, :video)
    end

    def get_id_param
      @id = params[:id]
    end

    def get_article
      @article = get_article_service.get_article(params[:id])

      redirect_to root_url if @article.nil?
    end
end

app/views/articles/_article.html.haml
%div{:id => "article-#{article.id}"}
  %div.col-md-12
    %h4.col-md-10
      = link_to article.name, article
    %span.pull-right
      = link_to t('articles.index.edit'), "javascript:void(0)", data: {toggle:"collapse", target:"#edit-article-#{article.id}"}
      = link_to t('articles.index.delete'), article, method: :delete, data: { confirm: 'Are you sure to delete this article?', remote: true }
  - if !article.created_at.nil?
    %div.entry.col-md-12
      %div.post-date
        = t('articles.index.post_text', time: article.created_at.strftime("%d/%m/%y"), author: article.author.name)

  = image_tag article.image_url
  %p
  - if !article.video.url.empty?
    = video_tag(article.video.url, controls: true)
    = image_tag article.video_thumb_url
  - if article.text.length > 20
    %p.text
      = truncate(article.text, length: 20)
    = link_to "Read more", "javascript:void(0)", onclick: "readmore(this, '#{article.text}')"
  - else
    %p
      = article.text
  %p
    %a{"data-toggle" => "collapse", "data-target" => "#new-comment-#{article.id}", href: "javascript:void(0)"}
      %span{id: "num-comments-#{article.id}"}
        = t('articles.index.comment', :count => article.comments.count)

  %div.collapse{:id => "new-comment-#{article.id}"}
    %div{:id => "comments-#{article.id}"}
      = render partial: "comment", collection: article.comments
    = form_tag article_comments_path(article), remote: true do
      %div.form-group
        = text_area_tag 'text', nil, required: true
      = button_to t('articles.index.save_comment'), remote: true, class:"btn btn-default"

  %div.collapse{:id => "edit-article-#{article.id}"}
    = form_for article, remote:true do |f|
      %div.form-group
        = f.label :name, t('name')
        = f.text_field :name, class:"form-control", required: true
      %div.form-group
        = f.label :text, t('text')
        = f.text_area :text, class:"form-control", required: true
      = button_to t('articles.index.save_article'), article, remote: true, class:"btn btn-default"

app/views/articles/_comment.html.haml
%p #{comment.text}

app/views/articles/create.js.erb
//$("<%= escape_javascript(render @article) %>").prependTo("#articles");

app/views/articles/destroy.js.erb
$("#article-<%= j @id %>").remove()

app/views/articles/edit.html.haml
= form_for @article, url: {action: "update"}  do |f|
  %div.form-group
    = f.label :name, t('name')
    = f.text_field :name, class:"form-control", required: true
  %div.form-group
    = f.label :text, t('text')
    = f.text_area :text, class:"form-control", required: true
  = f.submit t('save_article'), class:"btn btn-default"

app/views/articles/index.html.haml
= link_to t('.create_article'), "javascript:void(0)", class: "btn btn-danger", data: {toggle:"collapse", target:"#new-article"}
%div#new-article.collapse
  = form_for @article, :html => { :multipart => true } do |f|
    %div.form-group
      = f.label :name, t('.name')
      = f.text_field :name, class:"form-control", required: true
    %div.form-group
      = f.label :text, t('.text')
      = f.text_area :text, class:"form-control", required: true
    %div.form-group
      = f.label :image, t('.image')
      = f.file_field :image
    %div.form-group
      = f.label :video, t('.video')
      = f.file_field :video
    %div.form-group
      = f.label :author_id, t('.author')
      = collection_select(:article, :author_id, Author.all, :id, :name, {prompt: t('select_author')}, {class: "form-control", required: true})
    = button_to t('.save_article'), @article, class:"btn btn-default"
%div#articles
  = render @articles
%div.digg_pagination
  = paginate @articles, :remote => true

app/views/articles/index.js.erb
$('#articles').html('<%= escape_javascript render(@articles) %>');
$('.pagination').html('<%= escape_javascript(paginate(@articles, :remote => true).to_s) %>');

app/views/articles/new.html.haml
= form_for @article, url: {action: "create"} do |f|
  %div.form-group
    = f.label :name, t('name')
    = f.text_field :name, class:"form-control", required: true
  %div.form-group
    = f.label :text, t('text')
    = f.text_area :text, class:"form-control", required: true
  %div.form-group
    = f.label :author_id, t('author')
    = collection_select(:article, :author_id, Author.all, :id, :name, {prompt: t('select_author')}, {class: "form-control", required: true})
  = f.submit t('save_article'), class:"btn btn-default"

app/views/articles/show.html.haml
%h4= @article.name
- if !@article.created_at.nil?
    %div.entry
        %div.post-date
            = t('post_text', time: @article.created_at.strftime("%d/%m/%y"), author: @article.author.name)
%p= @article.text

%h3 #{@comments.length} Comments:
- @comments.each do |comment|
    %div.entry
        %p #{comment.text}

= form_tag article_comments_path(@article) do
    %div.form-group
        = text_area_tag 'text', nil, required: true
    = submit_tag t('save_comment'), class:"btn btn-default"

app/views/articles/update.js.erb
$("#article-<%= j @id %>").replaceWith("<%= escape_javascript(render @article) %>")