config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, controllers: { sessions: "authors/sessions" }
  resources :articles do
    resources :comments
  end
  root 'articles#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newspaper</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'script', 'jquery.tmpl.js', 'jquery.validate.min', 'additional-methods.min' %>

    <%= csrf_meta_tags %>
    <script type="text/html" id="article-template">
      <div id="article-${id}">
        <div class="col-md-12">
          <h4 class="col-md-10">
            <a href="/articles/${id}">${name}</a>
          </h4>
          <span class="pull-right">
            <a data-toggle="collapse" data-target="#edit-article-${id}" href="javascript:void(0)"><%= t('articles.index.edit') %></a>
            <a data-confirm="Are you sure to delete this article?" data-remote="true" rel="nofollow" data-method="delete" href="/articles/${id}"><%= t('articles.index.delete') %></a>
          </span>
        </div>

        <img src="${image_url}">
        <p></p>
        {{if video != ""}}
          <video src="${video}" controls></video>
        {{/if}}
        <p>${text}</p>
      </div>
    </script>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Newspaper</a>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="?locale=en">English</a></li>
              <li><a href="?locale=vi">Tiếng Việt</a></li>
              <% if author_signed_in? %>
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_author.name %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                          <%= link_to 'Log out', destroy_author_session_path, :method => :delete %>
                        </li>
                    </ul>
                </li>
              <% end %>
            </ul>
        </div>

    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

    <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container text-center">
            @Copyright 2015
        </div>
    </nav>

  </body>
</html>